[keymap]
# Navigation
"escape" = "Quit"
"down" = "SelectNext"
"up" = "SelectPrevious"
"left" = "MoveCursorLeft"
"right" = "MoveCursorRight"

# Preview scrolling
"ctrl+j" = "ScrollPreviewDown"
"ctrl+k" = "ScrollPreviewUp"
"ctrl+l" = "ScrollPreviewRight"
"ctrl+h" = "ScrollPreviewLeft"
"ctrl+u" = "IncreasePreview"
"ctrl+d" = "DecreasePreview"
"ctrl+y" = "CopyToClipboard"

# Search and input
"enter" = "Search"
"backspace" = "Backspace"

